import MSidebarMenu from './MSidebarMenu.vue'
import { ref } from 'vue'

export default {
  title: 'Sidebar Menu',
  component: MSidebarMenu,
}

const Template = (args) => ({
  components: {
    MSidebarMenu,
  },
  setup() {
    const items = ref([
      {
        "type": "button",
        "title": "Главная",
        "path": "/",
        "fast_action": null,
        "options": null,
        "active": true,
        "current": true,
      },
      {
        "type": "section",
        "title": "Управление товарами",
        "items": [
          {
            "type": "sub_menu",
            "title": "Товары",
            "fast_action": {
              "type": "fast_action",
              "path": "/products/create",
              "options": null,
              "active": false,
              "current": false,
            },
            "items": [
              {
                "type": "button",
                "title": "Все товары",
                "path": "/products",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "Создание товара",
                "path": "/products/create",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
            ],
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "sub_menu",
            "title": "Настройки",
            "fast_action": null,
            "items": [
              {
                "type": "button",
                "title": "SEO теги страниц",
                "path": "/settings/seo/pages",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "SEO теги изображений",
                "path": "/settings/seo/images",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
            ],
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Бренды",
            "path": "/brands",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Категории",
            "path": "/categories",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
        ],
        "options": null,
        "active": true,
        "current": false,
      },
      {
        "type": "section",
        "title": "Маркетинг",
        "items": [
          {
            "type": "sub_menu",
            "title": "Пользователи",
            "fast_action": null,
            "items": [
              {
                "type": "button",
                "title": "Все пользователи",
                "path": "/users",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "Создание пользователя",
                "path": "/users/create",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
            ],
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "sub_menu",
            "title": "Заказы",
            "fast_action": null,
            "items": [
              {
                "type": "button",
                "title": "Все заказы",
                "path": "/orders",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "Создание заказа",
                "path": "/orders/create",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
            ],
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Отзывы",
            "path": "/reviews",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "sub_menu",
            "title": "Блог",
            "fast_action": {
              "type": "fast_action",
              "path": "/blogs/create",
              "options": null,
              "active": false,
              "current": false,
            },
            "items": [
              {
                "type": "button",
                "title": "Все посты",
                "path": "/blogs",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "Создание поста",
                "path": "/blogs/create",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
            ],
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Отчеты",
            "path": "/reports",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "График работы",
            "path": "/work_times",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
        ],
        "options": null,
        "active": false,
        "current": false,
      },
      {
        "type": "section",
        "title": "Управление сайтом",
        "items": [
          {
            "type": "sub_menu",
            "title": "Виджет слайдер",
            "fast_action": null,
            "items": [
              {
                "type": "button",
                "title": "Главная. Обувь",
                "path": "/widget_sliders/shoes",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "Главная. Одежда",
                "path": "/widget_sliders/clothes",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
              {
                "type": "button",
                "title": "Главная. Аксессуары",
                "path": "/widget_sliders/accessories",
                "icon_url": null,
                "fast_action": null,
                "options": null,
                "active": false,
                "current": false,
              },
            ],
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Промокоды",
            "path": "/promo_codes",
            "fast_action": {
              "type": "fast_action",
              "path": "/promo_codes/create",
              "options": null,
              "active": false,
              "current": false,
            },
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Уведомления",
            "path": "/notifications",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
          {
            "type": "button",
            "title": "Баннеры",
            "path": "/banners",
            "fast_action": null,
            "options": null,
            "active": false,
            "current": false,
          },
        ],
        "options": null,
        "active": false,
        "current": false,
      },
    ])

    return { args, items }
  },
  template: `<m-sidebar-menu :items="items" v-bind="args"></m-sidebar-menu>`,
})

export const Default = Template.bind({})
Default.args = {
  maxWidth: 306,
}
